name: Deploy
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: install dependencies
        run: npm i
        working-directory: /root/Cyberia
      - name: restart service
        run: systemctl restart Cyberia
        working-directory: /root/Cyberia
